#!perl -w

use DNA;

CCAA CCAA AAGT CAGT TCCT CGCT ATGT AACA AGGA AGGA GTAT GGAT GGAT ATAT GGTT TAAT
ATGA CAGA CAGA TAGA TAGA CAGA TAGA TAGA CAGA CAGA TAGA CAGA TAGA CTGA TAGA CAGA
CAGA ATGA TAGA CAGA CAGA TCGA TCGA CAGA GAGA TAGA CAGA GTGA TAGA TAGA CAGA GAGA
TAGA CAGA CAGA TAGA CAGA TAGA ATGA TCGA TAGA TAGA CAGA CAGA TAGA TAGA TAGA CAGA
TAGA TCGA TAGA TAGA TAGA TAGA GTGA CAGA GTGT CAGA TAGA CAGA TAGA GTGA TAGA TCGA
TAGA TAGA GAGA TAGA TAGA TAGA CAGA TAGA CAGA TAGA CAGA GTGA TAGA TAGA ACGA TAGA
GGTT ATTT TTGG GATT ATTT GGTT TAAT GATT GGTT TAAT CGAT TCTT GCGA CCAA TAGA CGCA
TAGA CAGA TAGA CAGA CAGA TAGA TAGA TAGA CAGA TAGA CAGA GTGA TAGA CTGA CAGA CAGA
CTGA TAGA CAGA CAGA TAGA TAGA TAGA ACGA TAGA TAGA TAGA TAGA GAGA TAGA CAGA TAGA
TTGA GAGA CAGA TAGA CAGA ACGA TTGA TAGA TAGA ACGA CAGA TAGA CAGA TTGA CAGA CAGA
ATGA CAGA GAGA TTGA TAGA CAGA ACGA TAGA GTGA CAGA TAGA CAGA CAGA TAGA TAGA TTGA
TCGA ACGA TCGA ACGA CTGA CAGA CTGA TCGA CAGA TAGA TAGA CAGA TAGA CTGA TAGA TCGA
CGCA TAGA CCAA GGCT GCCT AACA TAGA CCAA GTAT GGAT GGAT ATAT GGTT TAAT GGTT ATTT
CAGA TAGA TAGA CAGA CAGA TAGA TAGA CAGA TAGA CAGA TAGA CTGA TTGA TCGA TAGA TCGA
CAGA ACGA CAGA TAGA ACGA TAGA ACGA TCGA TCGA TAGA CAGA TAGA TAGA CAGA TAGA ACGA
TAGA TAGA ACGA GTGA CAGA CAGA TAGA CAGA TAGA GTGA CAGA TAGA TAGA CAGA TAGA TAGA
TCGA TAGA CAGA TCGA CAGA CTGA TAGA CAGA GAGA TAGA ACGA TAGA TAGA TAGA GAGA TAGA
TAGA GTGA CAGA TAGA TAGA TCGA TAGA TAGA TAGA TAGA CAGA TAGA CAGA TAGA CAGA TAGA
TTAT GATT ATTT GGTT TAAT GATT GGTT TAAT CGAT TCTT CCAA 

